package com.hibernate.entities;
// Generated Oct 24, 2017 3:37:38 AM by Hibernate Tools 4.3.1



/**
 * CoursesStudents generated by hbm2java
 */
public class CoursesStudents  implements java.io.Serializable {


     private Integer id;
     private Courses courses;
     private Students students;

    public CoursesStudents() {
    }

    public CoursesStudents(Courses courses, Students students) {
       this.courses = courses;
       this.students = students;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }




}


