package com.hibernate.entities;
// Generated Oct 24, 2017 3:37:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students  implements java.io.Serializable {


     private Integer id;
     private String phone;
     private String faculty;
     private String firstName;
     private String lastName;
     private Date birthdate;
     private String address;
     private String gender;
     private Date registrationDate;
     private String paid;
     private Set coursesStudentses = new HashSet(0);

    public Students() {
    }

	
    public Students(String firstName, String lastName, Date registrationDate, String paid) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.registrationDate = registrationDate;
        this.paid = paid;
    }
    public Students(String phone, String faculty, String firstName, String lastName, Date birthdate, String address, String gender, Date registrationDate, String paid, Set coursesStudentses) {
       this.phone = phone;
       this.faculty = faculty;
       this.firstName = firstName;
       this.lastName = lastName;
       this.birthdate = birthdate;
       this.address = address;
       this.gender = gender;
       this.registrationDate = registrationDate;
       this.paid = paid;
       this.coursesStudentses = coursesStudentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(String faculty) {
        this.faculty = faculty;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = new Date();
    }
    public String getPaid() {
        return this.paid;
    }
    
    public void setPaid(String paid) {
        this.paid = paid;
    }
    public Set getCoursesStudentses() {
        return this.coursesStudentses;
    }
    
    public void setCoursesStudentses(Set coursesStudentses) {
        this.coursesStudentses = coursesStudentses;
    }




}


